### ISSUE TITLE
讨论并初步拟定项目需求

### ISSUE THREAD

**Issue by NeoBryant** [sysuswsad/mission_craft#4]
- [ ] 1. 确定第一次会议讨论时间；
    - [ ] 2019-4-1 周一下午
    - [ ] 2019-4-1 周一晚上
    - [ ] 2019-4-2 周二下午
    - [x] 2019-4-2 周二晚上
- [ ] 2. 集中讨论项目需求、功能；
- [ ] 3. 确定实现工具、方法；
- [ ] 4. 进行人员分工、任务分配；
- [ ] 5. 拟定任务计划与进度；

**Comment by ousuixin** [comment]
都可以
